# Site Settings
baseurl: ""
url : "https://kosy318.github.io"

# Blog Settings
theme_settings :
  title : Grape Theme
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Sooyeon Ko
    description : ...
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : c++
        value : 85  # Percent value
      - skill : python
        value : 70
      - skill : java
        value : 50
        
  # Icons
  icons :
    email: kosy1782@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: github.com/kosy318
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
