# Site Settings
baseurl: ""
url : "https://kosy318.github.io"

# Blog Settings
theme_settings :
  title : SOO
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Sooyeon Ko
    description : 사용자에게 편한 경험을 주는 개발자가 되고싶은 초보 개발자 입니다.
    experience :
      - start : 2017-03
        end : 2022-08
        experience : 부산대학교, 물리학과 + 컴퓨터공학과
      - start : 2022-07
        end : 2023-07
        experience : SSAFY 8th (Samsung SW Academy)
    skills : 
      - skill : c++
        value : 85  # Percent value
      - skill : python
        value : 70
      - skill : java
        value : 65
      - skill : javaScript
        value : 60
        
  # Icons
  icons :
    email: kosy1782@gmail.com # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: kosy318
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname : soo

# Pagination
paginate: 7
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
